name: Java Action 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Verify Java version
      run: java -version

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Copy jar to repo
      run: cp target/GitHubAction-0.0.1-SNAPSHOT.jar ./GitHubAction-0.0.1-SNAPSHOT.jar

    - name: Commit jar back to repository
      run: |
        git config --global user.name "Rahul-I2E"
        git config --global user.email "rahul.bhawsar@i2econsulting.com"
        git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git
        git add GitHubAction-0.0.1-SNAPSHOT.jar
        git commit -m "Add built jar"
        git push
  build2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
